import assert from 'node:assert/strict';
import fs from 'node:fs';
import { PLAN_LIMITS, PLAN_ORDER, PLAN_CAPABILITIES } from '../src/billing/planLimits.js';
import { canAccessCapability } from '../src/billing/planCapabilities.js';
import { hasPlanCapability } from '../api/_lib/limits.js';

assert.deepEqual(PLAN_ORDER, ['free','starter','pro','business']);
assert.equal(PLAN_LIMITS.free.products, 50);
assert.equal(PLAN_LIMITS.free.ai_claude_request, 0);
assert.equal(PLAN_LIMITS.trial.products, 2000);
assert.equal(PLAN_LIMITS.trial.ai_claude_request, 200);
assert.equal(PLAN_CAPABILITIES.free.branded_pdf, false);
assert.equal(PLAN_CAPABILITIES.starter.branded_pdf, true);
assert.equal(PLAN_CAPABILITIES.starter.bom_import, false);
assert.equal(PLAN_CAPABILITIES.pro.bom_import, true);
assert.equal(canAccessCapability({ dealer: { plan: 'free', subscription_status: 'active' } }, 'branded_pdf').ok, false);
assert.equal(canAccessCapability({ dealer: { plan: 'starter', subscription_status: 'active' } }, 'branded_pdf').ok, true);
assert.equal(hasPlanCapability('business', 'api_access'), true);
assert.match(fs.readFileSync('api/claude.js','utf8'), /assertPlanCapability\(auth, 'ai_import'\)/, '/api/claude must gate ai_import capability');
assert.match(fs.readFileSync('api/pdf-extract.js','utf8'), /assertPlanCapability\(auth, 'ai_import'\)/, '/api/pdf-extract must gate ai_import capability');
const app = fs.readFileSync('src/SmartQuote.jsx','utf8');
assert.match(app, /guardCapability\(cloud, "bom_import"/, 'BOM import client gate missing');
assert.match(app, /guardCapability\(cloud, "quote_variants_abc"/, 'quote variants client gate missing');
assert.match(app, /watermark: cloud\?\.enabled && !brandCapability\.ok/, 'PDF branded watermark fallback missing');
assert.match(fs.readFileSync('supabase/phase10_plan_capabilities.sql','utf8'), /interval '14 days'/, 'Trial should be 14 days');
console.log('✓ Phase 10 Free plan + capability gate smoke passed');
